// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {media} from '../models';

export function Analyze(arg1:main.AnalyzeRequest):Promise<main.AnalyzeResponse>;

export function CancelAnalysis(arg1:string):Promise<void>;

export function CancelDownload(arg1:string):Promise<void>;

export function ChooseDirectory(arg1:string):Promise<string>;

export function GetAnalysis(arg1:string):Promise<media.AnalysisResult>;

export function GetDefaultDirectory():Promise<main.DownloadDirectoryResponse>;

export function GetTask(arg1:string):Promise<media.DownloadTask>;

export function ListTasks():Promise<Array<media.DownloadTask>>;

export function RetryDownload(arg1:string):Promise<media.DownloadTask>;

export function SaveAs(arg1:string,arg2:string):Promise<string>;

export function SetDefaultDirectory(arg1:string):Promise<void>;

export function StartDownload(arg1:media.DownloadRequest):Promise<media.DownloadTask>;
