// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Analyze(arg1) {
  return window['go']['main']['App']['Analyze'](arg1);
}

export function AnalyzeWithBrowserSession(arg1) {
  return window['go']['main']['App']['AnalyzeWithBrowserSession'](arg1);
}

export function CancelAnalysis(arg1) {
  return window['go']['main']['App']['CancelAnalysis'](arg1);
}

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function ChooseDirectory(arg1) {
  return window['go']['main']['App']['ChooseDirectory'](arg1);
}

export function GetAnalysis(arg1) {
  return window['go']['main']['App']['GetAnalysis'](arg1);
}

export function GetDefaultDirectory() {
  return window['go']['main']['App']['GetDefaultDirectory']();
}

export function GetTask(arg1) {
  return window['go']['main']['App']['GetTask'](arg1);
}

export function GetYTDLPStatus() {
  return window['go']['main']['App']['GetYTDLPStatus']();
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function OpenContainingFolder(arg1) {
  return window['go']['main']['App']['OpenContainingFolder'](arg1);
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function Resolve(arg1, arg2, arg3) {
  return window['go']['main']['App']['Resolve'](arg1, arg2, arg3);
}

export function RetryDownload(arg1) {
  return window['go']['main']['App']['RetryDownload'](arg1);
}

export function SaveAs(arg1, arg2) {
  return window['go']['main']['App']['SaveAs'](arg1, arg2);
}

export function SetDefaultDirectory(arg1) {
  return window['go']['main']['App']['SetDefaultDirectory'](arg1);
}

export function StartDownload(arg1) {
  return window['go']['main']['App']['StartDownload'](arg1);
}

export function UpdateYTDLP() {
  return window['go']['main']['App']['UpdateYTDLP']();
}
